language: generic
addons:
  apt:
    packages:
      - qemu-system-arm
      - binfmt-support
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - DOCKER_CLI_EXPERIMENTAL=enabled
before_install:
  - sudo update-binfmts --display
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh
  - sudo usermod -aG docker ${USER}
  - docker buildx create --use
  - docker buildx build ./ --platform=linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/amd64,linux/i386 -t youcantbeserious/multiarch-k8dash:${COMMIT}
#  - docker build -t youcantbeserious/multiarch-k8dash:${COMMIT} .
  - export VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
  - wget https://github.com/aquasecurity/trivy/releases/download/v${VERSION}/trivy_${VERSION}_Linux-64bit.tar.gz
  - tar zxvf trivy_${VERSION}_Linux-64bit.tar.gz
script:
  - ./trivy --exit-code 0 --severity HIGH --no-progress trivy-ci-test:${COMMIT}
  - ./trivy --exit-code 1 --severity CRITICAL --no-progress trivy-ci-test:${COMMIT}
cache:
  directories:
    - $HOME/.cache/trivy
