replicaCount: 1
revisionHistoryLimit: 1
image:
  registry: herbrandson
  name: k8dash
  tag: latest
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 30
service:
  name: Node
  type: NodePort
  servicePort: 4654
  

